spring:
  application:
    name: blood-service-client
  datasource:
    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
    username: HR
    password: HR
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
       ddl-auto: update
       

       



server:
  port: 5051


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
