spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bhuvi56/cloud-configuration-2022.git
          search-paths:
          - '{application}'
          
          
          
          
server: 
  port: 8888         
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  